version: '3.8'

services:
  springapi-my-postgres-1:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - /Users/antonellabasalo/git/springAPI/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - springapi_my-network

  springapi-my-pgadmin-1:
    image: dpage/pgadmin4:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    networks:
      - springapi_my-network

networks:
  springapi_my-network:
    driver: bridge







